# yaml-language-server: $schema=./stars.schema.yaml

stars:
  - runway: 01L
    name: LUNIP4L
    waypoints:
      - { id: LUNIP, typicalSpeed: 250 }
      - { id: GM416, typicalAltitude: 11000, typicalSpeed: 220 }
      - { id: INSUV, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OGRAS, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIKLA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01R
    name: LUNIP4L
    waypoints:
      - { id: LUNIP, typicalSpeed: 250 }
      - { id: GM416, typicalAltitude: 11000, typicalSpeed: 220 }
      - { id: INSUV, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: NOSLA, typicalSpeed: 180 }
      - { id: XEMEN, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19L
    name: LUNIP4M
    waypoints:
      - { id: LUNIP, typicalSpeed: 250 }
      - { id: GM426, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM422, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: TITLA, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OSPAD, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIVTA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19R
    name: LUNIP4M
    waypoints:
      - { id: LUNIP, typicalSpeed: 250 }
      - { id: GM426, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM453, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: TITLA, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: ODUDI, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XINLO, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01L
    name: ADOPI3L
    waypoints:
      - { id: ADOPI, typicalSpeed: 250 }
      - { id: GM402, typicalAltitude: 10000, typicalSpeed: 220 }
      - { id: VALPU, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OGRAS, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIKLA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01R
    name: ADOPI3L
    waypoints:
      - { id: ADOPI, typicalSpeed: 250 }
      - { id: NIVDU, typicalSpeed: 250 }
      - { id: GM402, typicalAltitude: 10000, typicalSpeed: 220 }
      - { id: VALPU, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: NOSLA, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: NOSLA, typicalAltitude: 4000, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19R
    name: ADOPI3M
    waypoints:
      - { id: ADOPI, typicalSpeed: 250 }
      - { id: GM428, typicalAltitude: 10000, typicalSpeed: 220 }
      - { id: BAVAD, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: ODUDI, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XINLO, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19L
    name: ADOPI3M
    waypoints:
      - { id: ADOPI, typicalSpeed: 250 }
      - { id: GM428, typicalAltitude: 10000, typicalSpeed: 220 }
      - { id: BAVAD, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OSPAD, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIVTA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01L
    name: ESEBA4L
    waypoints:
      - { id: ESEBA, typicalSpeed: 250 }
      - { id: GM403, typicalAltitude: 10000, typicalSpeed: 220 }
      - { id: INSUV, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OGRAS, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIKLA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01R
    name: ESEBA4L
    waypoints:
      - { id: ESEBA, typicalSpeed: 250 }
      - { id: GM403, typicalAltitude: 10000, typicalSpeed: 220 }
      - { id: INSUV, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: NOSLA, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XEMEN, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19R
    name: ESEBA4M
    waypoints:
      - { id: ESEBA, typicalSpeed: 250 }
      - { id: GM422, typicalAltitude: 10000, typicalSpeed: 220 }
      - { id: TITLA, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: ODUDI, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XINLO, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19L
    name: ESEBA4M
    waypoints:
      - { id: ESEBA, typicalSpeed: 250 }
      - { id: GM422, typicalAltitude: 10000, typicalSpeed: 220 }
      - { id: TITLA, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OSPAD, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIVTA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01L
    name: BELGU3L
    waypoints:
      - { id: BELGU, typicalSpeed: 250 }
      - { id: GM400, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM402, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: VALPU, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OGRAS, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIKLA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01R
    name: BELGU3L
    waypoints:
      - { id: BELGU, typicalSpeed: 250 }
      - { id: GM400, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM402, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: VALPU, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: NOSLA, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XEMEN, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01R
    name: RIPAM3L
    waypoints:
      - { id: RIPAM, typicalSpeed: 250 }
      - { id: GM410, typicalAltitude: 11000, typicalSpeed: 220 }
      - { id: VALPU, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: NOSLA, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XEMEN, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01L
    name: RIPAM3L
    waypoints:
      - { id: RIPAM, typicalSpeed: 250 }
      - { id: GM410, typicalAltitude: 11000, typicalSpeed: 220 }
      - { id: VALPU, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OGRAS, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIKLA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19R
    name: RIPAM4M
    waypoints:
      - { id: RIPAM, typicalSpeed: 250 }
      - { id: GM427, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM428, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: BAVAD, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: ODUDI, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XINLO, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19L
    name: RIPAM4M
    waypoints:
      - { id: RIPAM, typicalSpeed: 250 }
      - { id: GM427, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM428, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: BAVAD, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OSPAD, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIVTA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19R
    name: BELGU3M
    waypoints:
      - { id: BELGU, typicalSpeed: 250 }
      - { id: GM433, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM434, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: BAVAD, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: ODUDI, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XINLO, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19L
    name: BELGU3M
    waypoints:
      - { id: BELGU, typicalSpeed: 250 }
      - { id: GM433, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM434, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: BAVAD, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OSPAD, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIVTA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01R
    name: INREX4L
    waypoints:
      - { id: INREX, typicalSpeed: 250 }
      - { id: GM401, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM403, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: INSUV, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: NOSLA, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XEMEN, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01L
    name: INREX4L
    waypoints:
      - { id: INREX, typicalSpeed: 250 }
      - { id: GM401, typicalAltitude: 9000, typicalSpeed: 250 }
      - { id: GM403, typicalAltitude: 9000, typicalSpeed: 220 }
      - { id: INSUV, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OGRAS, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIKLA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19L
    name: INREX4M
    waypoints:
      - { id: INREX, typicalSpeed: 250 }
      - { id: GM418, typicalAltitude: 11000, typicalSpeed: 220 }
      - { id: TITLA, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: OSPAD, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XIVTA, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 19R
    name: INREX4M
    waypoints:
      - { id: INREX, typicalSpeed: 250 }
      - { id: GM418, typicalAltitude: 11000, typicalSpeed: 220 }
      - { id: TITLA, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: ODUDI, typicalAltitude: 4000, typicalSpeed: 180 }
      - { id: XINLO, typicalAltitude: 3500, typicalSpeed: 170 }
      - { id: ENGM, typicalAltitude: 700 }

  - runway: 01L
    name: ELVUN-RNP-W
    waypoints:
      - { id: ELVUN, typicalAltitude: 5000, typicalSpeed: 200 }
      - { id: GM551, typicalAltitude: 3000, typicalSpeed: 180 }
      - { id: GM552, typicalAltitude: 2400, typicalSpeed: 170 }
      - { id: GM553, typicalAltitude: 1800, typicalSpeed: 150 }
      - { id: ENGM, typicalAltitude: 700 }
