# yaml-language-server: $schema=./airports.schema.yaml

airports:
  ENGM:
    location:
      latitude: 60.19250943987119
      longitude: 11.096549971455543
    runwayThresholds:
      01L:
        location:
          latitude: 60.18501045995491
          longitude: 11.073783755507158
        elevation: 681
        trueHeading: 16
      01R:
        location:
          latitude: 60.17580319639779
          longitude: 11.107782247775026
        elevation: 681
        trueHeading: 16
      19L:
        location:
          latitude: 60.20116653568569
          longitude: 11.12244616482607
        elevation: 681
        trueHeading: 196
      19R:
        location:
          latitude: 60.21601904982423
          longitude: 11.091636783048877
        elevation: 681
        trueHeading: 196

  ENBR:
    location:
      latitude: 60.2938676
      longitude: 5.221587222
    runwayThresholds:
      35:
        location:
          latitude: 60.28254992002292
          longitude: 5.221778147674375
        elevation: 146
        trueHeading: 170
      17:
        location:
          latitude: 60.30422545984025
          longitude: 5.214462654076689
        elevation: 166
        trueHeading: 350
  EDDF:
    location:
      latitude: 50.037054
      longitude: 8.570456
    runwayThresholds:
      07L:
        location:
          latitude: 50.037054
          longitude: 8.497078
        elevation: 304
        trueHeading: 70
      07C:
        location:
          latitude: 50.032617
          longitude: 8.53463
        elevation: 328
        trueHeading: 70
      07R:
        location:
          latitude: 50.027542
          longitude: 8.534174
        elevation: 327
        trueHeading: 70
      25L:
        location:
          latitude: 50.040052
          longitude: 8.586529
        elevation: 361
        trueHeading: 250
      25C:
        location:
          latitude: 50.045127
          longitude: 8.586981
        elevation: 363
        trueHeading: 250
      25R:
        location:
          latitude: 50.045825
          longitude: 8.533716
        elevation: 351
        trueHeading: 250
    independentRunwaySystems:
      - ["07L"]
      - ["07C", "07R"]
      - ["25R"]
      - ["25C", "25L"]
