# yaml-language-server: $schema=./settings-schema.json

timelines:
  ENGM:
    - title: "01ALL"
      right:
        runways: ["01L", "01R"]

    - title: "19ALL"
      right:
        runways: ["19L", "19R"]

    - title: "19R/19L"
      left:
        runways: ["19R"]
      right:
        runways: ["19L"]

    - title: "01L/01R"
      left:
        runways: ["01L"]
      right:
        runways: ["01R"]

  ENBR:
    - title: "BR17"
      right:
        runways: ["17"]

    - title: "BR35"
      right:
        runways: ["35"]

    - title: "ENBR ALL"
      right:
        runways: ["17", "35"]

connectionConfig:
  atcClient:
    host: "localhost"
    port: 12345
  api:
    host: "https://aman-dman-api.fly.dev"
