name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Decide version
        shell: bash
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV          

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build C++ Project
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Release /p:PluginVersion="${{env.VERSION}}" /p:Contributors="TBD" euroscope-bridge /p:Platform=x86

      - name: Build Gradle Project
        run: |
          cd aman-dman-client
          .\gradlew.bat shadowJar

      - name: Create artifacts directory structure
        shell: bash
        run: |
          mkdir -p artifacts/config
          cp euroscope-bridge/Release/*.dll artifacts/
          cp aman-dman-client/build/libs/*.jar artifacts/
          cp -r aman-dman-client/config/* artifacts/config/

      - name: Zip artifacts
        run: |
          powershell -Command "Compress-Archive -Path artifacts\* -DestinationPath aman-dman-${{ env.VERSION }}.zip"

      - name: Upload to GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: aman-dman-${{ env.VERSION }}.zip
          draft: true       # <-- create a draft instead of publishing immediately
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AMAN-DMAN-${{ env.VERSION }}
          path: aman-dman-${{ env.VERSION }}.zip
